# Generated by Django 3.1 on 2020-09-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoli', '0002_auto_20200906_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Enlace'),
        ),
    ]
